import type { Diagnostic, EmittedFile } from '@girih/core';
import { emittedFile } from '@girih/core';
import type { ComponentIR, LoadedExtension } from '@girih/spec';
import { renderComponentCss, renderExtensionCss } from './css.js';
import { renderCheckboxComponent } from './templates/checkbox.js';
import { renderDialogComponent, renderHeadlessAdapter } from './templates/dialog.js';
import { renderElementComponent } from './templates/element.js';

/** Pinned by the tool: the headless layer is a template implementation detail. */
const BASE_UI_VERSION = '1.0.0-rc.0';

export interface GenerateReactOptions {
  /** Published package name, e.g. '@acme/design-system'. */
  packageName: string;
  /** CSS variable prefix (matches the css generator). */
  prefix: string;
  /** Published version for package.json; defaults to '0.0.0-dev' until `girih publish` sets it. */
  version?: string;
  /** Class prefix for component classes; defaults to the CSS variable prefix. */
  classPrefix?: string;
  runtimePackage?: string;
}

export interface GenerateReactExtras {
  /** Validated workspace extensions (defineVariant). */
  extensions?: LoadedExtension[];
  /** Ejected components: name → user-owned source, stitched in verbatim. */
  ejected?: Record<string, string>;
}

export interface GenerateReactResult {
  files: EmittedFile[];
  diagnostics: Diagnostic[];
}

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** Render one component's source through its template — also what `girih eject` snapshots. */
export function renderComponentSource(ir: ComponentIR, options: { classPrefix: string; runtimePackage: string }): string {
  if (ir.template === 'checkbox') return renderCheckboxComponent(ir, options);
  if (ir.template === 'dialog') return renderDialogComponent(ir, options);
  return renderElementComponent(ir, options);
}

const REF_ELEMENT_TYPES: Record<string, string> = {
  a: 'HTMLAnchorElement',
  button: 'HTMLButtonElement',
  div: 'HTMLDivElement',
  input: 'HTMLInputElement',
  span: 'HTMLSpanElement',
};

function renderExtensionComponent(
  extension: LoadedExtension['extension'],
  baseIr: ComponentIR,
  options: { classPrefix: string; runtimePackage: string; sourceFile: string },
): string {
  const refType = REF_ELEMENT_TYPES[baseIr.element] ?? 'HTMLElement';
  const extensionClass = `${options.classPrefix}-x-${kebab(extension.name)}`;
  const doc = extension.description ? `/** ${extension.description} */\n` : '';
  return `/* Generated by girih — do not edit. Source of truth: ${options.sourceFile} */
import { forwardRef } from 'react';
import { cx } from '${options.runtimePackage}';
import { ${baseIr.name} } from './${baseIr.name}';
import type { ${baseIr.name}Props } from './${baseIr.name}';

${doc}export const ${extension.name} = forwardRef<${refType}, ${baseIr.name}Props>(function ${extension.name}(
  { className, ...rest },
  ref,
) {
  return <${baseIr.name} ref={ref} className={cx('${extensionClass}', className)} {...rest} />;
});
`;
}

/**
 * ComponentIR[] → React package source. Deterministic: same IRs, same bytes.
 * tokens.css / tokens.d.ts are the css generator's job — the CLI composes both
 * into the same output directory.
 */
export function generateReact(
  irs: ComponentIR[],
  options: GenerateReactOptions,
  extras: GenerateReactExtras = {},
): GenerateReactResult {
  const diagnostics: Diagnostic[] = [];
  const files: EmittedFile[] = [];
  const classPrefix = options.classPrefix ?? options.prefix;
  const runtimePackage = options.runtimePackage ?? '@girih/react-runtime';
  const sorted = [...irs].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const extensions = [...(extras.extensions ?? [])].sort((a, b) =>
    a.extension.name < b.extension.name ? -1 : 1,
  );
  const byName = new Map(sorted.map((ir) => [ir.name, ir]));
  const needsHeadless = sorted.some((ir) => ir.template === 'dialog');

  for (const ir of sorted) {
    for (const aria of ir.accessibility.aria) {
      if (aria.state !== 'loading' && aria.state !== 'disabled') {
        diagnostics.push({
          code: 'GIRIH5001',
          severity: 'warning',
          message: `'${ir.name}' maps aria attributes to state '${aria.state}', which the '${ir.template}' template only expresses in CSS — the attributes are not wired.`,
          ...(ir.sourceFile ? { file: ir.sourceFile } : {}),
          path: `accessibility.aria.${aria.state}`,
        });
      }
    }

    const source = extras.ejected?.[ir.name] ?? renderComponentSource(ir, { classPrefix, runtimePackage });
    files.push(emittedFile(`src/${ir.name}.tsx`, source));
  }

  for (const { file, extension } of extensions) {
    const baseIr = byName.get(extension.extends);
    if (!baseIr) continue; // validated upstream (GIRIH4034)
    files.push(
      emittedFile(
        `src/${extension.name}.tsx`,
        renderExtensionComponent(extension, baseIr, { classPrefix, runtimePackage, sourceFile: file }),
      ),
    );
  }

  if (needsHeadless) {
    files.push(emittedFile('src/internal/headless.ts', renderHeadlessAdapter()));
  }

  const componentCss = sorted
    .map((ir) => renderComponentCss(ir, { prefix: options.prefix, classPrefix }))
    .filter(Boolean);
  const extensionCss = extensions
    .map(({ extension }) => {
      const baseIr = byName.get(extension.extends);
      return baseIr ? renderExtensionCss(extension, baseIr, { prefix: options.prefix, classPrefix }) : '';
    })
    .filter(Boolean);
  files.push(
    emittedFile(
      'styles/components.css',
      `/* Generated by girih — do not edit. Structure only; every value is a token var(). */\n\n${[...componentCss, ...extensionCss].join('\n\n')}\n`,
    ),
  );

  const exportedNames = [...sorted.map((ir) => ir.name), ...extensions.map(({ extension }) => extension.name)];
  const propTypeExports = sorted.map((ir) =>
    ir.template === 'dialog' ? `export type { ${ir.name}PopupProps } from './${ir.name}';` : `export type { ${ir.name}Props } from './${ir.name}';`,
  );
  const indexLines = [
    '/* Generated by girih — do not edit. */',
    ...exportedNames.map((name) => `export { ${name} } from './${name}';`),
    ...propTypeExports,
    `export { BrandProvider, useBrand, cx } from '${runtimePackage}';`,
    '',
  ];
  files.push(emittedFile('src/index.ts', indexLines.join('\n')));

  files.push(
    emittedFile(
      'package.json',
      JSON.stringify(
        {
          name: options.packageName,
          version: options.version ?? '0.0.0-dev',
          description: 'Generated by girih — do not edit. Regenerate with `girih generate react`.',
          type: 'module',
          sideEffects: ['**/*.css'],
          // Publish-shaped: points at compiled dist/ (produced by `girih build`).
          // Dev/demo consumers import ./src/* by deep path; these exports drive
          // the published package and any exports-aware bundler after a build.
          main: './dist/index.js',
          module: './dist/index.js',
          types: './dist/index.d.ts',
          exports: {
            '.': { types: './dist/index.d.ts', import: './dist/index.js' },
            './styles/tokens.css': './styles/tokens.css',
            './styles/components.css': './styles/components.css',
          },
          files: ['dist', 'styles', 'README.md'],
          peerDependencies: { react: '>=18' },
          dependencies: {
            [runtimePackage]: '^0.1.0',
            ...(needsHeadless ? { '@base-ui-components/react': BASE_UI_VERSION } : {}),
          },
        },
        null,
        2,
      ) + '\n',
    ),
  );

  files.push(
    emittedFile(
      'README.md',
      `# ${options.packageName}

Generated by girih — **do not edit**; regenerate with \`girih generate react\`.

## Build before publish

\`package.json\` \`exports\` point at compiled \`dist/\`. Run \`girih build\` to
produce it (per-file ESM + \`.d.ts\`), then \`girih publish\` to version and
publish. Inside the workspace, dev tools import \`./src/*\` directly, so you can
iterate without a build.

## Usage

\`\`\`tsx
import { Button, BrandProvider } from '${options.packageName}';
import '${options.packageName}/styles/tokens.css';
import '${options.packageName}/styles/components.css';
\`\`\`
`,
    ),
  );

  return { files, diagnostics };
}
