import type { Diagnostic, EmittedFile } from '@girih/core';
import { emittedFile } from '@girih/core';
import type { ComponentIR } from '@girih/spec';
import { renderComponentCss } from './css.js';
import { renderElementComponent } from './templates/element.js';

export interface GenerateReactOptions {
  /** Published package name, e.g. '@acme/design-system'. */
  packageName: string;
  /** CSS variable prefix (matches the css generator). */
  prefix: string;
  /** Class prefix for component classes; defaults to the CSS variable prefix. */
  classPrefix?: string;
  runtimePackage?: string;
}

export interface GenerateReactResult {
  files: EmittedFile[];
  diagnostics: Diagnostic[];
}

/**
 * ComponentIR[] → React package source. Deterministic: same IRs, same bytes.
 * tokens.css / tokens.d.ts are the css generator's job — the CLI composes both
 * into the same output directory.
 */
export function generateReact(irs: ComponentIR[], options: GenerateReactOptions): GenerateReactResult {
  const diagnostics: Diagnostic[] = [];
  const files: EmittedFile[] = [];
  const classPrefix = options.classPrefix ?? options.prefix;
  const runtimePackage = options.runtimePackage ?? '@girih/react-runtime';
  const sorted = [...irs].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  for (const ir of sorted) {
    for (const aria of ir.accessibility.aria) {
      if (aria.state !== 'loading' && aria.state !== 'disabled') {
        diagnostics.push({
          code: 'GIRIH5001',
          severity: 'warning',
          message: `'${ir.name}' maps aria attributes to state '${aria.state}', which the element template only expresses in CSS — the attributes are not wired.`,
          ...(ir.sourceFile ? { file: ir.sourceFile } : {}),
          path: `accessibility.aria.${aria.state}`,
        });
      }
    }
    files.push(
      emittedFile(`src/${ir.name}.tsx`, renderElementComponent(ir, { classPrefix, runtimePackage })),
    );
  }

  const componentCss = sorted
    .map((ir) => renderComponentCss(ir, { prefix: options.prefix, classPrefix }))
    .filter(Boolean)
    .join('\n\n');
  files.push(
    emittedFile(
      'styles/components.css',
      `/* Generated by girih — do not edit. Structure only; every value is a token var(). */\n\n${componentCss}\n`,
    ),
  );

  const indexLines = [
    '/* Generated by girih — do not edit. */',
    ...sorted.map((ir) => `export { ${ir.name} } from './${ir.name}';`),
    ...sorted.map((ir) => `export type { ${ir.name}Props } from './${ir.name}';`),
    `export { BrandProvider, useBrand, cx } from '${runtimePackage}';`,
    '',
  ];
  files.push(emittedFile('src/index.ts', indexLines.join('\n')));

  files.push(
    emittedFile(
      'package.json',
      JSON.stringify(
        {
          name: options.packageName,
          version: '0.0.0-dev',
          description: 'Generated by girih — do not edit. Regenerate with `girih generate react`.',
          type: 'module',
          sideEffects: ['**/*.css'],
          exports: {
            '.': { import: './src/index.ts' },
            './styles/tokens.css': './styles/tokens.css',
            './styles/components.css': './styles/components.css',
          },
          peerDependencies: { react: '>=18' },
          dependencies: { [runtimePackage]: '^0.1.0' },
        },
        null,
        2,
      ) + '\n',
    ),
  );

  files.push(
    emittedFile(
      'README.md',
      `# ${options.packageName}

Generated by girih — **do not edit**; regenerate with \`girih generate react\`.

## M3 constraints (lifted in M6)

- **Source-shipped**: \`exports\` points at TypeScript source. Consume it with a
  bundler (esbuild, Vite, Next.js) — plain \`tsc\` NodeNext resolution will not
  work with the extensionless internal imports.
- **Workspace-only**: the \`${runtimePackage}\` dependency is not published yet,
  so this package resolves only inside the girih workspace (or via a file/link
  install). \`girih publish\` (M6) adds a compiled \`dist/\` and real versioning.

## Usage

\`\`\`tsx
import { Button, BrandProvider } from '${options.packageName}';
import '${options.packageName}/styles/tokens.css';
import '${options.packageName}/styles/components.css';
\`\`\`
`,
    ),
  );

  return { files, diagnostics };
}
