import type { ComponentIR } from '@faravahar/girih-spec';
import type { TemplateOptions } from './element.js';

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/**
 * Checkbox template: a styled native <input type="checkbox"> — real form
 * semantics, keyboard behavior, and :checked for free; the visual box and
 * glyph are drawn in CSS so every color flows through tokens.
 */
export function renderCheckboxComponent(ir: ComponentIR, options: TemplateOptions): string {
  const { name } = ir;
  const className = `${options.classPrefix}-${kebab(name)}`;
  const doc = ir.description ? `/** ${ir.description} */\n` : '';

  const variantProps = ir.variants
    .map(
      (axis) =>
        `export type ${name}${axis.axis.charAt(0).toUpperCase()}${axis.axis.slice(1)} = ${axis.values.map((v) => `'${v}'`).join(' | ')};`,
    )
    .join('\n');
  const propLines = ir.variants.map((axis) => `  ${axis.axis}?: ${name}${axis.axis.charAt(0).toUpperCase()}${axis.axis.slice(1)};`);
  const destructured = [...ir.variants.map((axis) => `${axis.axis} = '${axis.default}'`), 'className'];
  const dataAttrs = ir.variants.map((axis) => `      data-${kebab(axis.axis)}={${axis.axis}}`).join('\n');

  return `/* Generated by girih — do not edit. Source of truth: components/${kebab(name)}.spec.ts */
import { forwardRef } from 'react';
import type { ComponentPropsWithoutRef } from 'react';
import { cx } from '${options.runtimePackage}';

${variantProps}

export interface ${name}Props extends Omit<ComponentPropsWithoutRef<'input'>, ${['type', ...ir.variants.map((a) => a.axis)].map((n) => `'${n}'`).join(' | ')}> {
${propLines.join('\n')}
}

${doc}export const ${name} = forwardRef<HTMLInputElement, ${name}Props>(function ${name}(
  { ${destructured.join(', ')}, ...rest },
  ref,
) {
  return (
    <input
      ref={ref}
      type="checkbox"
      className={cx('${className}', className)}
${dataAttrs ? `${dataAttrs}\n` : ''}      {...rest}
    />
  );
});
`;
}

/** Structural CSS the checkbox template owns: the box, the glyph, the states. */
export function checkboxStructuralCss(base: string): string[] {
  return [
    `${base} {
  appearance: none;
  display: inline-grid;
  place-content: center;
  margin: 0;
  border: 1px solid transparent;
  cursor: pointer;
}`,
    `${base}::after {
  content: '';
  width: 0.55em;
  height: 0.3em;
  border-left: 2px solid currentColor;
  border-bottom: 2px solid currentColor;
  transform: rotate(-45deg) translate(5%, -15%);
  opacity: 0;
}`,
    `${base}:checked::after {
  opacity: 1;
}`,
    `${base}:focus-visible {
  outline: 2px solid currentColor;
  outline-offset: 2px;
}`,
    `${base}:disabled {
  cursor: not-allowed;
  opacity: 0.55;
}`,
  ];
}
