import { componentClassName, kebabName } from '@faravahar/girih-core';
import type { ComponentIR } from '@faravahar/girih-spec';
import type { TemplateOptions } from './element.js';

/**
 * Dialog template: behavior (focus trap, dismissal, aria wiring) is delegated
 * to Base UI through the emitted adapter; girih owns the class hooks and the
 * token-driven styling. The spec parameterizes parts and the size axis.
 */
export function renderDialogComponent(ir: ComponentIR, options: TemplateOptions): string {
  const { name } = ir;
  const base = componentClassName(options.classPrefix, name);
  const doc = ir.description ? `/** ${ir.description} */\n` : '';
  const sizeAxis = ir.variants.find((axis) => axis.axis === 'size');
  const sizeType = sizeAxis ? `export type ${name}Size = ${sizeAxis.values.map((v) => `'${v}'`).join(' | ')};\n\n` : '';
  // Base UI types className as string | (state) => string; the girih contract is
  // plain strings, so narrow it — otherwise the cx() call cannot typecheck.
  const popupProps = `export interface ${name}PopupProps extends Omit<ComponentPropsWithoutRef<typeof BaseDialog.Popup>, 'className'> {
  className?: string;${sizeAxis ? `\n  size?: ${name}Size;` : ''}
}`;
  const popupDestructure = sizeAxis ? `{ size = '${sizeAxis.default}', className, children, ...rest }` : `{ className, children, ...rest }`;
  const popupSizeAttr = sizeAxis ? `\n      data-size={size}` : '';

  return `/* Generated by girih — do not edit. Source of truth: components/${kebabName(name)}.contract.ts */
import { forwardRef } from 'react';
import type { ComponentPropsWithoutRef } from 'react';
import { BaseDialog } from './internal/headless';
import { cx } from '${options.runtimePackage}';

${sizeType}${popupProps}

${doc}const Popup = forwardRef<HTMLDivElement, ${name}PopupProps>(function ${name}Popup(
  ${popupDestructure},
  ref,
) {
  return (
    <BaseDialog.Portal>
      <BaseDialog.Backdrop className="${base}-backdrop" />
      <BaseDialog.Popup ref={ref} className={cx('${base}-popup', className)}${popupSizeAttr} {...rest}>
        {children}
      </BaseDialog.Popup>
    </BaseDialog.Portal>
  );
});

type StringClassName = { className?: string };

function Title({ className, ...rest }: Omit<ComponentPropsWithoutRef<typeof BaseDialog.Title>, 'className'> & StringClassName) {
  return <BaseDialog.Title className={cx('${base}-title', className)} {...rest} />;
}

function Description({ className, ...rest }: Omit<ComponentPropsWithoutRef<typeof BaseDialog.Description>, 'className'> & StringClassName) {
  return <BaseDialog.Description className={cx('${base}-description', className)} {...rest} />;
}

export const ${name} = {
  /** Controls open state; accepts open / defaultOpen / onOpenChange. */
  Root: BaseDialog.Root,
  /** Renders its child as the trigger via the render prop, e.g. <${name}.Trigger render={<Button/>}>. */
  Trigger: BaseDialog.Trigger,
  /** Backdrop + centered popup, portalled to <body>. */
  Popup,
  Title,
  Description,
  /** Closes the dialog; render your own control: <${name}.Close render={<Button variant="secondary"/>}>. */
  Close: BaseDialog.Close,
};
`;
}

/** The one file allowed to import the headless library — swapping it is a template concern. */
export function renderHeadlessAdapter(): string {
  return `/* Generated by girih — do not edit. */
/**
 * Adapter over the headless behavior layer. Only this file may import it:
 * swapping Base UI out is a girih template upgrade, never a spec change.
 */
export { Dialog as BaseDialog } from '@base-ui-components/react/dialog';
`;
}

/** Structural CSS the dialog template owns: positioning, layering, sizing plumbing. */
export function dialogStructuralCss(base: string, prefix: string): string[] {
  return [
    `.${base}-backdrop {
  position: fixed;
  inset: 0;
  z-index: 40;
}`,
    `.${base}-popup {
  position: fixed;
  inset: 0;
  margin: auto;
  height: fit-content;
  width: calc(100% - 2 * var(--${prefix}-dialog-gutter, 16px));
  z-index: 50;
  display: flex;
  flex-direction: column;
  outline: none;
}`,
    `.${base}-title {
  margin: 0;
}`,
    `.${base}-description {
  margin: 0;
}`,
  ];
}
