import type { ComponentIR } from '@faravahar/girih-spec';

const REF_ELEMENT_TYPES: Record<string, string> = {
  a: 'HTMLAnchorElement',
  button: 'HTMLButtonElement',
  div: 'HTMLDivElement',
  input: 'HTMLInputElement',
  label: 'HTMLLabelElement',
  span: 'HTMLSpanElement',
  textarea: 'HTMLTextAreaElement',
};

const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

export interface TemplateOptions {
  /** CSS class prefix, e.g. 'ds' → .ds-button */
  classPrefix: string;
  runtimePackage: string;
}

/**
 * The "styled element" template: a presentational host element whose entire
 * styling contract flows through data attributes + CSS variables. Behavioral
 * components (Dialog on Base UI) get their own template in M5.
 */
export function renderElementComponent(ir: ComponentIR, options: TemplateOptions): string {
  const { name, element } = ir;
  const refType = REF_ELEMENT_TYPES[element] ?? 'HTMLElement';
  const className = `${options.classPrefix}-${kebab(name)}`;
  const hasLoading = ir.states.includes('loading');
  const hasDisabled = ir.states.includes('disabled');
  const hasInvalid = ir.states.includes('invalid');
  const nativeDisabled = ['button', 'input', 'textarea', 'select'].includes(element);

  const variantTypes = ir.variants
    .map((axis) => `export type ${name}${capitalize(axis.axis)} = ${axis.values.map((v) => `'${v}'`).join(' | ')};`)
    .join('\n');

  // Spec-authored prop names must shadow native attributes (input's size?: number
  // would otherwise clash with a 'size' axis) — omit them from the inherited props.
  const localNames = [...ir.variants.map((a) => a.axis), ...ir.props.map((p) => p.name)];
  const inherited =
    localNames.length > 0
      ? `Omit<ComponentPropsWithoutRef<'${element}'>, ${localNames.map((n) => `'${n}'`).join(' | ')}>`
      : `ComponentPropsWithoutRef<'${element}'>`;

  const propLines: string[] = [
    ...ir.variants.map((axis) => `  ${axis.axis}?: ${name}${capitalize(axis.axis)};`),
    ...ir.props.map((p) => `  ${p.name}?: boolean;`),
  ];
  if (hasLoading) propLines.push('  loading?: boolean;');
  if (hasInvalid) propLines.push('  invalid?: boolean;');
  // Non-native hosts have no built-in disabled — the template owns the prop.
  if (hasDisabled && !nativeDisabled) propLines.push('  disabled?: boolean;');

  const destructured: string[] = [
    ...ir.variants.map((axis) => `${axis.axis} = '${axis.default}'`),
    ...ir.props.map((p) => `${p.name} = ${p.default}`),
  ];
  if (hasLoading) destructured.push('loading = false');
  if (hasInvalid) destructured.push('invalid = false');
  destructured.push('className');
  if (hasDisabled) destructured.push(nativeDisabled ? 'disabled' : 'disabled = false');
  if (element === 'button') destructured.push(`type = 'button'`);
  if (ir.childrenRequired) destructured.push('children');

  const attrs: string[] = [
    `ref={ref}`,
    `className={cx('${className}', className)}`,
    ...ir.variants.map((axis) => `data-${kebab(axis.axis)}={${axis.axis}}`),
    ...ir.props.map((p) => `data-${kebab(p.name)}={${p.name} || undefined}`),
  ];
  if (hasLoading) attrs.push(`data-loading={loading || undefined}`);
  if (hasInvalid) {
    attrs.push(`data-invalid={invalid || undefined}`);
    // aria-invalid is the announced state; data-invalid is the styling hook. One
    // prop drives both so they can never disagree.
    attrs.push(`aria-invalid={invalid || undefined}`);
  }
  const wiredAria = new Set<string>();
  for (const aria of ir.accessibility.aria) {
    if (aria.state === 'loading' && hasLoading) {
      for (const [attr, value] of Object.entries(aria.attributes)) {
        attrs.push(`${attr}={loading ? '${value}' : undefined}`);
        wiredAria.add(attr);
      }
    }
    if (aria.state === 'disabled' && hasDisabled && !nativeDisabled) {
      for (const [attr, value] of Object.entries(aria.attributes)) {
        attrs.push(`${attr}={disabled ? '${value}' : undefined}`);
        wiredAria.add(attr);
      }
    }
  }
  if (hasDisabled && nativeDisabled) {
    attrs.push(hasLoading ? `disabled={disabled || loading}` : `disabled={disabled}`);
  }
  if (hasDisabled && !nativeDisabled && !wiredAria.has('aria-disabled')) {
    // Without this the [aria-disabled="true"] state selector could never activate.
    attrs.push(`aria-disabled={disabled ? 'true' : undefined}`);
  }
  if (element === 'button') attrs.push('type={type}');
  if (ir.accessibility.role && ir.accessibility.role !== element) {
    attrs.push(`role="${ir.accessibility.role}"`);
  }

  const attrBlock = attrs.map((a) => `      ${a}`).join('\n');
  const jsx = ir.childrenRequired
    ? `    <${element}\n${attrBlock}\n      {...rest}\n    >\n      {children}\n    </${element}>`
    : `    <${element}\n${attrBlock}\n      {...rest}\n    />`;
  const doc = ir.description ? `/** ${ir.description} */\n` : '';

  return `/* Generated by girih — do not edit. Source of truth: components/${kebab(name)}.spec.ts */
import { forwardRef } from 'react';
import type { ComponentPropsWithoutRef } from 'react';
import { cx } from '${options.runtimePackage}';

${variantTypes}

export interface ${name}Props extends ${inherited} {
${propLines.join('\n')}
}

${doc}export const ${name} = forwardRef<${refType}, ${name}Props>(function ${name}(
  { ${destructured.join(', ')}, ...rest },
  ref,
) {
  return (
${jsx}
  );
});
`;
}
