import StyleDictionary from 'style-dictionary';
import type { DesignTokens } from 'style-dictionary/types';
import type { Diagnostic, EmittedFile } from '@girih/core';
import { emittedFile } from '@girih/core';
import { toNestedDtcg } from '@girih/tokens';
import type { TokenBuildResult } from '@girih/tokens';
import { cssVarName } from './naming.js';

export interface GenerateCssOptions {
  prefix: string;
  defaultBrand: string;
  selector: 'data-attribute' | 'class';
}

export interface GenerateCssResult {
  files: EmittedFile[];
  diagnostics: Diagnostic[];
}

/** Composite $values (shadow, typography, …) must be flattened to CSS strings, not stringified objects. */
const CSS_TRANSFORMS = [
  'name/girih',
  'color/css',
  'fontFamily/css',
  'cubicBezier/css',
  'shadow/css/shorthand',
  'typography/css/shorthand',
  'border/css/shorthand',
  'transition/css/shorthand',
  'strokeStyle/css/shorthand',
];

function brandSelector(brand: string, kind: GenerateCssOptions['selector']): string {
  return kind === 'class' ? `.brand-${brand}` : `[data-brand="${brand}"]`;
}

/** Deterministic regardless of the host locale — plain code-unit comparison. */
function byCodeUnit(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * Emit one stylesheet: a :root block for the default brand (with var() references
 * preserved, so brand overrides cascade), plus one scoped block per non-default
 * brand. A brand block re-emits the union of that brand's overrides and the default
 * brand's overrides — the latter so a default-brand override never leaks into other
 * brands through :root.
 */
export async function generateCss(build: TokenBuildResult, options: GenerateCssOptions): Promise<GenerateCssResult> {
  const diagnostics: Diagnostic[] = [];
  const blocks: string[] = [];

  diagnostics.push(...detectVarNameCollisions(build, options));
  if (diagnostics.some((d) => d.severity === 'error')) {
    return { files: [], diagnostics };
  }

  const defaultOverrides = build.overrides.get(options.defaultBrand) ?? [];
  const brands = [...build.graphs.keys()].sort((a, b) =>
    a === options.defaultBrand ? -1 : b === options.defaultBrand ? 1 : byCodeUnit(a, b),
  );

  for (const brand of brands) {
    const isDefault = brand === options.defaultBrand;
    const blockPaths = new Set(isDefault ? [] : [...(build.overrides.get(brand) ?? []), ...defaultOverrides]);
    if (!isDefault && blockPaths.size === 0) continue;

    const graph = build.graphs.get(brand)!;

    try {
      const sd = new StyleDictionary({
        tokens: toNestedDtcg({ tokens: graph.tokens }) as DesignTokens,
        log: { verbosity: 'silent', warnings: 'disabled' },
        hooks: {
          transforms: {
            'name/girih': {
              type: 'name',
              transform: (token, platform) => cssVarName(platform?.prefix ?? options.prefix, token.path).slice(2),
            },
          },
        },
        platforms: {
          css: {
            transforms: CSS_TRANSFORMS,
            prefix: options.prefix,
            files: [
              {
                destination: 'tokens.css',
                format: 'css/variables',
                options: {
                  selector: isDefault ? ':root' : brandSelector(brand, options.selector),
                  outputReferences: true,
                },
                ...(isDefault ? {} : { filter: (token) => blockPaths.has(token.path.join('.')) }),
              },
            ],
          },
        },
      });
      const formatted = await sd.formatPlatform('css');
      const output = formatted[0]?.output;
      if (typeof output === 'string') {
        diagnostics.push(...detectUnserializableValues(output, brand));
        blocks.push(output.trimEnd());
      }
    } catch (error) {
      diagnostics.push({
        code: 'GIRIH3001',
        severity: 'error',
        message: `CSS generation failed for brand '${brand}': ${(error as Error).message}`,
      });
    }
  }

  const banner = `/* Generated by girih — do not edit. Source of truth: tokens/ and brands/. */\n\n`;
  const files = [emittedFile('tokens.css', banner + blocks.join('\n\n') + '\n'), generateTokenTypes(build, options)];
  return { files, diagnostics };
}

/** TokenPath string-literal union — this is what makes token references type-checked in specs. */
export function generateTokenTypes(build: TokenBuildResult, options: GenerateCssOptions): EmittedFile {
  const graph = build.graphs.get(options.defaultBrand) ?? [...build.graphs.values()][0];
  const paths = graph ? [...graph.tokens.keys()].sort(byCodeUnit) : [];
  const union = (literals: string[]): string[] =>
    literals.length === 0
      ? ['  never;']
      : literals.map((l, i) => `  | '${l}'${i === literals.length - 1 ? ';' : ''}`);
  const lines = [
    '/* Generated by girih — do not edit. */',
    '',
    'export type TokenPath =',
    ...union(paths),
    '',
    'export type TokenCssVariable =',
    ...union(paths.map((p) => cssVarName(options.prefix, p))),
    '',
  ];
  return emittedFile('tokens.d.ts', lines.join('\n'));
}

/**
 * Two distinct token paths may map to the same CSS variable name
 * (e.g. 'color.primary.hover' vs 'color.primary-hover', or case-only differences).
 * That is a silent last-one-wins in CSS, so it fails the build.
 */
function detectVarNameCollisions(build: TokenBuildResult, options: GenerateCssOptions): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  const graph = build.graphs.get(options.defaultBrand) ?? [...build.graphs.values()][0];
  if (!graph) return diagnostics;

  const byVarName = new Map<string, string[]>();
  for (const path of graph.tokens.keys()) {
    const varName = cssVarName(options.prefix, path);
    if (!byVarName.has(varName)) byVarName.set(varName, []);
    byVarName.get(varName)!.push(path);
  }
  for (const [varName, paths] of byVarName) {
    if (paths.length > 1) {
      diagnostics.push({
        code: 'GIRIH3003',
        severity: 'error',
        message: `Tokens ${paths.map((p) => `'${p}'`).join(' and ')} both map to the CSS variable '${varName}'.`,
        path: paths[0]!,
        help: 'Rename one of them — CSS variable names are case-insensitive here and join segments with "-".',
      });
    }
  }
  return diagnostics;
}

/** A value the transform chain could not flatten stringifies as '[object Object]' — fail loudly. */
function detectUnserializableValues(cssBlock: string, brand: string): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];
  for (const line of cssBlock.split('\n')) {
    if (line.includes('[object Object]') || line.includes('[object Array]')) {
      const variable = line.trim().split(':')[0] ?? line.trim();
      diagnostics.push({
        code: 'GIRIH3002',
        severity: 'error',
        message: `'${variable}' (brand '${brand}') has a composite value no CSS transform could flatten.`,
        help: 'Give the token a supported $type (shadow, typography, border, transition, cubicBezier, fontFamily) or split it into scalar tokens.',
      });
    }
  }
  return diagnostics;
}
