import type { Diagnostic, EmittedFile } from '@faravahar/girih-core';
import { CSS_LAYERS, cssLayer, emittedFile, extensionClassName, kebabName } from '@faravahar/girih-core';
import type { ComponentIR, LoadedExtension } from '@faravahar/girih-spec';
import { renderComponentCss, renderExtensionCss } from './css.js';
import { renderHeadlessAdapter } from './templates/dialog.js';
import { refElementType, renderElementComponent } from './templates/element.js';
import { TEMPLATE_REGISTRY } from './templates/registry.js';

/** Pinned by the tool: the headless layer is a template implementation detail. */
const BASE_UI_VERSION = '1.0.0-rc.0';

/**
 * Range for the runtime in every generated package.json. This lands in a package
 * the *consumer* publishes, so an unsatisfiable range breaks their install, not
 * ours — and `^0.x` admits only that one minor. test/runtime-range.test.ts pins it
 * to the runtime's real version so a lockstep bump cannot leave it behind.
 */
export const RUNTIME_VERSION_RANGE = '^0.4.0';

export interface GenerateReactOptions {
  /** Published package name, e.g. '@acme/design-system'. */
  packageName: string;
  /** CSS variable prefix (matches the css generator). */
  prefix: string;
  /** Published version for package.json; defaults to '0.0.0-dev' until `girih bake` sets it. */
  version?: string;
  /** Class prefix for component classes; defaults to the CSS variable prefix. */
  classPrefix?: string;
  runtimePackage?: string;
}

export interface GenerateReactExtras {
  /** Validated workspace extensions (defineVariant). */
  extensions?: LoadedExtension[];
  /** Ejected components: name → user-owned source, stitched in verbatim. */
  ejected?: Record<string, string>;
}

export interface GenerateReactResult {
  files: EmittedFile[];
  diagnostics: Diagnostic[];
}

/** Render one component's source through its template — also what `girih eject` snapshots. */
export function renderComponentSource(ir: ComponentIR, options: { classPrefix: string; runtimePackage: string }): string {
  const render = TEMPLATE_REGISTRY[ir.template]?.render ?? renderElementComponent;
  return render(ir, options);
}

function renderExtensionComponent(
  extension: LoadedExtension['extension'],
  baseIr: ComponentIR,
  options: { classPrefix: string; runtimePackage: string; sourceFile: string },
): string {
  const refType = refElementType(baseIr.element);
  const extensionClass = extensionClassName(options.classPrefix, extension.name);
  const doc = extension.description ? `/** ${extension.description} */\n` : '';
  return `/* Generated by girih — do not edit. Source of truth: ${options.sourceFile} */
import { forwardRef } from 'react';
import { cx } from '${options.runtimePackage}';
import { ${baseIr.name} } from './${kebabName(baseIr.name)}';
import type { ${baseIr.name}Props } from './${kebabName(baseIr.name)}';

${doc}export const ${extension.name} = forwardRef<${refType}, ${baseIr.name}Props>(function ${extension.name}(
  { className, ...rest },
  ref,
) {
  return <${baseIr.name} ref={ref} className={cx('${extensionClass}', className)} {...rest} />;
});
`;
}

/**
 * ComponentIR[] → React package source. Deterministic: same IRs, same bytes.
 * tokens.css / tokens.d.ts are the css generator's job — the CLI composes both
 * into the same output directory.
 */
export function generateReact(irs: ComponentIR[], options: GenerateReactOptions, extras: GenerateReactExtras = {}): GenerateReactResult {
  const diagnostics: Diagnostic[] = [];
  const files: EmittedFile[] = [];
  const classPrefix = options.classPrefix ?? options.prefix;
  const runtimePackage = options.runtimePackage ?? '@faravahar/girih-react-runtime';
  const sorted = [...irs].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const extensions = [...(extras.extensions ?? [])].sort((a, b) => (a.extension.name < b.extension.name ? -1 : 1));
  const byName = new Map(sorted.map((ir) => [ir.name, ir]));
  const needsHeadless = sorted.some((ir) => ir.template === 'dialog');

  for (const ir of sorted) {
    for (const aria of ir.accessibility.aria) {
      if (aria.state !== 'loading' && aria.state !== 'disabled') {
        diagnostics.push({
          code: 'GIRIH5001',
          severity: 'warning',
          message: `'${ir.name}' maps aria attributes to state '${aria.state}', which the '${ir.template}' template only expresses in CSS — the attributes are not wired.`,
          ...(ir.sourceFile ? { file: ir.sourceFile } : {}),
          path: `accessibility.aria.${aria.state}`,
          help: 'Move the aria mapping to a component whose template wires attributes, or drop it — leaving it in place would imply accessibility support that is not emitted.',
        });
      }
    }

    const source = extras.ejected?.[ir.name] ?? renderComponentSource(ir, { classPrefix, runtimePackage });
    files.push(emittedFile(`src/${kebabName(ir.name)}.tsx`, source));
  }

  for (const { file, extension } of extensions) {
    const baseIr = byName.get(extension.extends);
    if (!baseIr) continue; // validated upstream (GIRIH4034)
    files.push(
      emittedFile(
        `src/${kebabName(extension.name)}.tsx`,
        renderExtensionComponent(extension, baseIr, { classPrefix, runtimePackage, sourceFile: file }),
      ),
    );
  }

  if (needsHeadless) {
    files.push(emittedFile('src/internal/headless.ts', renderHeadlessAdapter()));
  }

  const componentCss = sorted.map((ir) => renderComponentCss(ir, { prefix: options.prefix, classPrefix })).filter(Boolean);
  const extensionCss = extensions
    .map(({ extension }) => {
      const baseIr = byName.get(extension.extends);
      return baseIr ? renderExtensionCss(extension, baseIr, { prefix: options.prefix, classPrefix }) : '';
    })
    .filter(Boolean);
  files.push(
    emittedFile(
      'styles/components.css',
      `/* Generated by girih — do not edit. Structure only; every value is a token var(). */\n\n${cssLayer(
        CSS_LAYERS.components,
        [...componentCss, ...extensionCss].join('\n\n'),
      )}\n`,
    ),
  );

  const exportedNames = [...sorted.map((ir) => ir.name), ...extensions.map(({ extension }) => extension.name)];
  const propTypeExports = sorted.map((ir) =>
    ir.template === 'dialog'
      ? `export type { ${ir.name}PopupProps } from './${kebabName(ir.name)}';`
      : `export type { ${ir.name}Props } from './${kebabName(ir.name)}';`,
  );
  const indexLines = [
    '/* Generated by girih — do not edit. */',
    // The exported identifier stays PascalCase while the module specifier is kebab-case:
    // JSX resolves a lowercase tag to an HTML element, so `<badge>` would emit a literal
    // <badge> node rather than the component. Only the file names are ours to choose.
    ...exportedNames.map((name) => `export { ${name} } from './${kebabName(name)}';`),
    ...propTypeExports,
    `export { BrandProvider, useBrand, cx } from '${runtimePackage}';`,
    '',
  ];
  files.push(emittedFile('src/index.ts', indexLines.join('\n')));

  files.push(
    emittedFile(
      'package.json',
      JSON.stringify(
        {
          name: options.packageName,
          version: options.version ?? '0.0.0-dev',
          description: 'Generated by girih — do not edit. Regenerate with `girih generate react`.',
          type: 'module',
          sideEffects: ['**/*.css'],
          // Publish-shaped: points at compiled dist/ (produced by `girih build`).
          // Dev/demo consumers import ./src/* by deep path; these exports drive
          // the published package and any exports-aware bundler after a build.
          main: './dist/index.js',
          module: './dist/index.js',
          types: './dist/index.d.ts',
          exports: {
            '.': { types: './dist/index.d.ts', import: './dist/index.js' },
            './styles/tokens.css': './styles/tokens.css',
            './styles/components.css': './styles/components.css',
          },
          files: ['dist', 'styles', 'README.md'],
          peerDependencies: { react: '>=18' },
          dependencies: {
            [runtimePackage]: RUNTIME_VERSION_RANGE,
            ...(needsHeadless ? { '@base-ui-components/react': BASE_UI_VERSION } : {}),
          },
        },
        null,
        2,
      ) + '\n',
    ),
  );

  files.push(
    emittedFile(
      'README.md',
      `# ${options.packageName}

Generated by girih — **do not edit**; regenerate with \`girih generate react\`.

## Build before publish

\`package.json\` \`exports\` point at compiled \`dist/\`. Run \`girih build\` to
produce it (per-file ESM + \`.d.ts\`), then \`girih bake\` to version it and stage
it in \`.ds/baked\` for you to publish however you like. Inside the workspace, dev
tools import \`./src/*\` directly, so you can iterate without a build.

## Usage

\`\`\`tsx
import { Button, BrandProvider } from '${options.packageName}';
import '${options.packageName}/styles/tokens.css';
import '${options.packageName}/styles/components.css';
\`\`\`
`,
    ),
  );

  return { files, diagnostics };
}
